import { Question, BrandingConfig } from '../types';
import { jsPDF } from 'jspdf';
import { matchingRowLetter, ROMAN_ROW_SUFFIX } from '../../utils/matchingPaperColumns';

export interface AnswerKeyConfig {
  topic: string;
  questions: Question[];
  brandConfig?: BrandingConfig;
  filename?: string;
  /** When true, two-column layout with explanations (dense packing, extra pages as needed). */
  includeExplanations?: boolean;
}

const PAGE_W = 210;
const PAGE_H = 297;

function stripHtmlToPlain(html: string | undefined | null): string {
  if (!html) return '';
  if (typeof document !== 'undefined') {
    const d = document.createElement('div');
    d.innerHTML = html;
    return (d.textContent || '').replace(/\s+/g, ' ').trim();
  }
  return String(html)
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function formatCorrectAnswerShort(q: Question): string {
  if (q.type === 'matching' && Array.isArray(q.correctMatches) && q.correctMatches.length) {
    const parts = q.correctMatches.map((bIdx, aIdx) => {
      const r = ROMAN_ROW_SUFFIX[bIdx] ?? String(bIdx + 1);
      return `${matchingRowLetter(aIdx)}→${r}`;
    });
    return parts.join(', ');
  }
  const idx = Math.max(0, Math.min(25, q.correctIndex ?? 0));
  return `(${String.fromCharCode(65 + idx)})`;
}

function drawHeader(
  doc: jsPDF,
  topic: string,
  brandConfig: BrandingConfig | undefined,
  subtitle: string,
  margin: number,
  top: number
) {
  doc.setFont('helvetica', 'bold');
  if (brandConfig?.name) {
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(brandConfig.name.toUpperCase(), margin, top);
  }
  doc.setFontSize(11);
  doc.text(subtitle, PAGE_W - margin, top, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(90);
  doc.text(topic, PAGE_W - margin, top + 5, { align: 'right' });
  doc.setDrawColor(0);
  doc.setLineWidth(0.35);
  doc.line(margin, top + 10, PAGE_W - margin, top + 10);
  doc.setTextColor(0);
}

function drawFooter(doc: jsPDF, brandConfig: BrandingConfig | undefined) {
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7.5);
  doc.setTextColor(140);
  doc.text(`Generated by ${brandConfig?.name || 'KiwiTeach'}`, PAGE_W / 2, PAGE_H - 8, { align: 'center' });
  doc.setTextColor(0);
}

async function generateAnswerSheetCompact({
  topic,
  questions,
  brandConfig,
  filename,
}: AnswerKeyConfig): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const MARGIN = 12;
  const HEADER_TOP = 12;
  const HEADER_BLOCK = 24;
  const FOOTER = 12;
  const usableH = PAGE_H - HEADER_BLOCK - FOOTER - MARGIN;
  const usableW = PAGE_W - 2 * MARGIN;

  let numCols = 4;
  let fontSize = 9;
  let lineMm = fontSize * 0.48;

  const capacity = () => Math.max(1, Math.floor(usableH / lineMm)) * numCols;

  while (capacity() < questions.length && numCols < 8) {
    numCols += 1;
  }
  while (capacity() < questions.length && fontSize > 6.5) {
    fontSize -= 0.5;
    lineMm = fontSize * 0.48;
  }

  drawHeader(doc, topic, brandConfig, 'ANSWER KEY', MARGIN, HEADER_TOP);

  doc.setFont('courier', 'normal');
  doc.setFontSize(fontSize);
  doc.setTextColor(0);

  const colW = usableW / numCols;
  const itemsPerColumn = Math.max(1, Math.ceil(questions.length / numCols));
  const startY = HEADER_BLOCK + MARGIN;

  let y = startY;
  let currentColumn = 0;
  for (let i = 0; i < questions.length; i++) {
    if (i > 0 && i % itemsPerColumn === 0) {
      currentColumn += 1;
      y = startY;
    }
    if (currentColumn >= numCols) {
      doc.addPage();
      drawHeader(doc, topic, brandConfig, 'ANSWER KEY (cont.)', MARGIN, HEADER_TOP);
      doc.setFont('courier', 'normal');
      doc.setFontSize(fontSize);
      doc.setTextColor(0);
      currentColumn = 0;
      y = startY;
    }
    const x = MARGIN + currentColumn * colW;
    const q = questions[i];
    const ans = formatCorrectAnswerShort(q);
    const text = `${String(i + 1).padStart(2, ' ')}. ${ans}`;
    doc.text(text, x, y);
    y += lineMm;
  }

  drawFooter(doc, brandConfig);
  doc.save(filename || `${topic.replace(/[/\\?%*:|"<>]/g, '_').replace(/\s+/g, '_')}_Answer_Key.pdf`);
}

async function generateAnswerSheetWithExplanations({
  topic,
  questions,
  brandConfig,
  filename,
}: AnswerKeyConfig): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const MARGIN = 12;
  const COL_GAP = 5;
  const HEADER_TOP = 12;
  const HEADER_BLOCK = 26;
  const FOOTER = 14;
  const MAX_Y = PAGE_H - FOOTER;
  const COL_W = (PAGE_W - 2 * MARGIN - COL_GAP) / 2;
  const startY = HEADER_BLOCK + MARGIN - 4;

  drawHeader(doc, topic, brandConfig, 'ANSWER KEY + EXPLANATIONS', MARGIN, HEADER_TOP);

  const labelSize = 8.5;
  const bodySize = 8;
  const labelLineH = 3.6;
  const bodyLineH = 3.35;
  const paraGap = 2;

  let yL = startY;
  let yR = startY;
  const xL = MARGIN;
  const xR = MARGIN + COL_W + COL_GAP;

  const newPage = () => {
    doc.addPage();
    drawHeader(doc, topic, brandConfig, 'ANSWER KEY + EXPLANATIONS (cont.)', MARGIN, HEADER_TOP);
    yL = startY;
    yR = startY;
  };

  const placeBlock = (blockH: number, draw: (x: number, y: number) => void) => {
    let useLeft = yL <= yR;
    let x = useLeft ? xL : xR;
    let y = useLeft ? yL : yR;

    if (y + blockH > MAX_Y) {
      const otherY = useLeft ? yR : yL;
      const otherX = useLeft ? xR : xL;
      if (otherY + blockH <= MAX_Y) {
        useLeft = !useLeft;
        x = useLeft ? xL : xR;
        y = useLeft ? yL : yR;
      } else {
        newPage();
        x = xL;
        y = yL;
        useLeft = true;
      }
    }

    draw(x, y);

    const newY = y + blockH + paraGap;
    if (useLeft) yL = newY;
    else yR = newY;
  };

  const maxColBodyH = MAX_Y - startY - labelLineH * 3;
  const maxExplLinesPerChunk = Math.max(4, Math.floor(maxColBodyH / bodyLineH));

  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const n = i + 1;
    const ans = formatCorrectAnswerShort(q);
    const expl = stripHtmlToPlain(q.explanation);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(labelSize);
    const headLine = `${n}. ${ans}`;
    const headW = doc.getTextWidth(headLine);
    const headLines = headW > COL_W - 1 ? (doc.splitTextToSize(headLine, COL_W - 1) as string[]) : [headLine];
    const headH = headLines.length * labelLineH;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(bodySize);
    const explLines = expl
      ? (doc.splitTextToSize(expl, COL_W - 1) as string[])
      : ([] as string[]);

    const emitChunk = (lines: string[], showHead: boolean) => {
      const explH = lines.length > 0 ? lines.length * bodyLineH + (showHead ? 1 : 0) : 0;
      const blockH = (showHead ? headH : 0) + explH;
      placeBlock(blockH, (x, y) => {
        let yy = y;
        if (showHead) {
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(labelSize);
          doc.setTextColor(0);
          for (const line of headLines) {
            doc.text(line, x, yy);
            yy += labelLineH;
          }
        }
        if (lines.length) {
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(bodySize);
          doc.setTextColor(35);
          for (const line of lines) {
            doc.text(line, x, yy);
            yy += bodyLineH;
          }
        }
        doc.setTextColor(0);
      });
    };

    if (explLines.length === 0) {
      emitChunk([], true);
      continue;
    }

    let offset = 0;
    let first = true;
    while (offset < explLines.length) {
      const roomLines = first
        ? Math.max(1, maxExplLinesPerChunk - Math.ceil(headH / bodyLineH))
        : maxExplLinesPerChunk;
      const chunk = explLines.slice(offset, offset + Math.max(1, roomLines));
      offset += chunk.length;
      emitChunk(chunk, first);
      first = false;
    }
  }

  drawFooter(doc, brandConfig);
  doc.save(
    filename ||
      `${topic.replace(/[/\\?%*:|"<>]/g, '_').replace(/\s+/g, '_')}_Answer_Key_With_Explanations.pdf`
  );
}

export async function generateAnswerKeyPDF(config: AnswerKeyConfig): Promise<void> {
  if (config.includeExplanations) {
    return generateAnswerSheetWithExplanations(config);
  }
  return generateAnswerSheetCompact(config);
}
