import { Question, BrandingConfig } from '../types';
import { jsPDF } from 'jspdf';

interface AnswerKeyConfig {
  topic: string;
  questions: Question[];
  brandConfig?: BrandingConfig;
  filename?: string;
}

export const generateAnswerKeyPDF = async ({
  topic,
  questions,
  brandConfig,
  filename
}: AnswerKeyConfig): Promise<void> => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const PAGE_WIDTH = 210;
    const MARGIN = 15;
    const FONT_SIZE = 10;
    const LINE_HEIGHT = 7;
    const NUM_COLUMNS = 4;
    const finalFilename = filename || `${topic.replace(/\s+/g, '_')}_Answer_Key.pdf`;

    // --- Header ---
    doc.setFont('helvetica', 'bold');
    if (brandConfig?.name) {
        doc.setFontSize(16);
        doc.text(brandConfig.name.toUpperCase(), MARGIN, MARGIN + 5);
    }
    doc.setFontSize(12);
    doc.text('ANSWER KEY', PAGE_WIDTH - MARGIN, MARGIN + 5, { align: 'right' });
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(topic, PAGE_WIDTH - MARGIN, MARGIN + 11, { align: 'right' });
    
    doc.setLineWidth(0.5);
    doc.line(MARGIN, MARGIN + 15, PAGE_WIDTH - MARGIN, MARGIN + 15);

    // --- Body: Answer Columns ---
    doc.setFont('courier', 'normal');
    doc.setFontSize(FONT_SIZE);
    doc.setTextColor(0);

    const itemsPerColumn = Math.ceil(questions.length / NUM_COLUMNS);
    const columnWidth = (PAGE_WIDTH - (MARGIN * 2)) / NUM_COLUMNS;
    const startY = MARGIN + 25;
    let y = startY;
    let currentColumn = 0;

    for (let i = 0; i < questions.length; i++) {
        if (i > 0 && i % itemsPerColumn === 0) {
            currentColumn++;
            y = startY; // Reset y for new column
        }
        
        const x = MARGIN + (currentColumn * columnWidth);
        const q = questions[i];
        // Fix: Use `q.correctIndex` which is defined in the `Question` type. `correct_index` is not part of the type.
        const correctOption = `(${String.fromCharCode(65 + (q.correctIndex ?? 0))})`;
        const text = `${String(i + 1).padStart(3, ' ')}. ${correctOption}`;
        
        doc.text(text, x, y);
        y += LINE_HEIGHT;
    }

    // --- Footer ---
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(150);
    const footerText = `Generated by ${brandConfig?.name || 'KiwiTeach'}`;
    doc.text(footerText, PAGE_WIDTH / 2, 297 - 10, { align: 'center' });

    doc.save(finalFilename);
};
